image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

unit_test:
  stage: test
  variables:
    NODE_ENV: test
  before_script:
    - npm install
  script:
    - npm run test

test_run:
  services:
    - postgres:11-alpine
  stage: test
  variables:
    POSTGRES_DB: frmfeedback
    POSRGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    RDS_HOSTNAME: postgres
    RDS_USERNAME: postgres
    RDS_PASSWORD: postgres
    RDS_DB_NAME: frmfeedback
    TYPEORM_SYNC: 'true'
  before_script:
    - npm install
  script:
    - npm run start:gitlab
  only:
    - master
