image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build

unit_test:
  stage: test
  variables:
    NODE_ENV: test
  before_script:
    - npm install
  script:
    - npm run test

build_test:
  services:
    - postgres:11-alpine
  stage: build
  variables:
    POSTGRES_DB: frmfeedback
    POSRGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    NODE_ENV: development
    RDS_HOSTNAME: postgres
    RDS_USERNAME: postgres
    RDS_PASSWORD: postgres
    RDS_DB_NAME: frmfeedback
    TYPEORM_SYNC: true
  before_script:
    - npm install
  script:
    - npm run start
