version: '3.1'
services:
  PostgreSQL:
    container_name: PostgresFrmFeedback
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=frmfeedback
      TZ: 'Europe/Moscow'
      PGTZ: 'Europe/Moscow'
    volumes:
      -./docker-volumes/postgresql:/var/lib/postgresql