version: '2'
services:
  PostgreSQL:
    container_name: PostgresFrmFeedback
    image: postgres:11
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    network_mode: 'host'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frmfeedback
      - TZ=Europe/Moscow
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql
