version: '2'
services:
  PostgreSQL:
    container_name: PostgresFrmFeedback
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: frmfeedback
      POSTGRES_PASSWORD: F3Vx7J8uZ3V5
      POSTGRES_DB: frmfeedback
      TZ: Europe/Moscow
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql11

  frm_feedback:
    image: perpendikulyar/frm_feedback
    container_name: FrmFeedback
    restart: always
    depends_on:
      - PostgreSQL
    environment:
      - NODE_ENV=firstRun
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Europe/Moscow
      - TZ=Europe/Moscow
      - RDS_HOSTNAME=PostgreSQL
      - RDS_PORT=5432
      - RDS_USERNAME=frmfeedback
      - RDS_PASSWORD=F3Vx7J8uZ3V5
      - RDS_DB_NAME=frmfeedback
      - TYPEORM_SYNC=true
      - PORT=3000
      - JWT_SECRET=XR8kvxWs6HXv
    ports:
      - '3000:3000'
